### ISSUE TITLE
Post jar files in Releases

### ISSUE THREAD

**Issue by TwinkleToes777** [mrgeneralq/sleep-most#123]
Hey, it is really nice that you are posting updates on GitHub, it is very convenient. But could you upload jar file together with Releases too? So I can read the release from my feed reader and download the file directly from there.

**Comment by mrgeneralq** [comment]
Hello Twinkletoes

I'm not quite sure how I would approach it. If you are experienced in this feel free to contact me on discord. My apologies for the inconvenience.

Kind regards

Quinten

**Comment by TwinkleToes777** [comment]
Sorry, but I do not use Discord. You can do this by attaching a plugin .jar file when posting a new Release at https://github.com/mrgeneralq/sleep-most/releases

**Comment by mrgeneralq** [comment]
I added the Jar for the latest version
