### ISSUE TITLE
/sm kick or pressing kick button does not cancel the sleep

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/sleep-most#125]
Kicking someone out of their bed only works before the skip-delay is over. Even if the nightcycle-animation is not over, it will still continue to skip the night.

Expected behaviour: When nightcycle-animation starts, I expect the cycle to stop if the player gets kicked from bed.

Video for explaining: https://www.loom.com/share/668439c8ecc44c2d9863cf8a93a9932c

Additional suggestion: Autocomplete username when doing /sm kick.

**Comment by mrgeneralq** [comment]
This issue cannot be considered an issue because if the animation the animation is already running, people would start trolling by leaving the bed
