### ISSUE TITLE
plugin issue 1.19

### ISSUE THREAD

**Issue by FielSteve** [mrgeneralq/sleep-most#128]
![Screenshot (15)](https://user-images.githubusercontent.com/88622954/173289885-9bb9306c-1ce8-4b78-b49a-0628784ea708.png)
although the plugin has server interaction 1.19 like after sleeping overnight it will spam a rather long line on cmd, i'm afraid that when players sleep again at night it will spam on cmd causing server lag, hope this will be fixed soon~ plugin very cool!~

**Comment by mrgeneralq** [comment]
Hello

Thank you for reporting this issue. I am investigating this and will back to you asap.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
This issue is now resolved as of **v5.0.3**.
