### ISSUE TITLE
Integration with Gsit

### ISSUE THREAD

**Issue by RhinoCD** [mrgeneralq/sleep-most#131]
Gsit has a /lay feature and a config option to skip the night. It would be awesome to get gsit hooked with sleep-most, so players who have access to /lay will count towards sleeping!

https://www.spigotmc.org/resources/gsit-modern-sit-seat-and-chair-lay-and-crawl-plugin-1-13-x-1-19-x.62325/

**Comment by mrgeneralq** [comment]
@RhinoCD 
Feature added along with 2 new flags:
gsit-hook [true/false]
gsit-sleep [true/false]

Awaiting final tests. When completed it will be released with the upcoming release

**Comment by RhinoCD** [comment]
lets go! ilysm
