### ISSUE TITLE
Missing message when trying to do commands when plugin is not enabled in that world

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/sleep-most#132]
If you have forgotten to enable SleepMost in a world, you will not receive an error message when executing commands. When doing for example /sm sleep, no message appears in chat. 

Expected behaviour: If plugin is disabled in that world, and a player tries to execute a player command, I expect a "Sleepmost is not enabled in this world" message.

**Comment by Villmarksjenta** [comment]
test

**Comment by Villmarksjenta** [comment]
test

**Comment by Villmarksjenta** [comment]
test

**Comment by Villmarksjenta** [comment]
test

**Comment by Villmarksjenta** [comment]
test

**Comment by mrgeneralq** [comment]
Added a check in the /sleep command to check if world is enabled
