### ISSUE TITLE
New version missing 2 messages in messages.yml

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/sleep-most#134]
Current version is missing 2 messages in messages.yml. These messages existed before the messages.yml, and was deleted by mistake.

  night-skipped: '&bThe night was skipped!'
  
  storm-skipped: '&bThe storm was skipped!'

**Comment by mrgeneralq** [comment]
After investigating I've noticed that the message never got removed, it just got overwritten. This was the message key:
user.night-skipped

And there was a new message key that looked like this:
user.night-skipped.title

This resulted in the previous messages being removed and overwritten by the title message.

**Solution**: message keys have been renamed to:

- user.night-skipped-title
- user.night-skipped-subtitle
- user.storm-skipped-title
- user.storm-skipped-subtitle
- user.night-skipped-chat
- user.storm-skipped-chat
