### ISSUE TITLE
Ability to customize how long a day or night should be

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/sleep-most#135]
I want to be able to customize how many (real time) minutes a day or night should consist of.
Default (real time) minutes is currently 7.5 minutes for each day and night. I want to be able to etc. have 10 minutes day and so on.

(Suggestion by J41MIE#7152 on discord)

**Comment by mrgeneralq** [comment]
Added new flag "longer-night-duration" <int> . Time will freeze during mid night for x amount of seconds. This even requires to night to pass by MidNight - 500 seconds where the night is scheduled. For the moment no chance, 100% guarantee. To disable longer nights, just put duration to 0.
