### ISSUE TITLE
Tab-complete for /sm resetflag

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/sleep-most#137]
/sm resetflag does not have a tab-complete.
/sm getflag and /sm setflag both has tab-complete.

Could be considered both a bug and suggestion, to be able to have tab-complete for resetflag aswell.
![image](https://user-images.githubusercontent.com/59545209/178970873-c22e4f1c-dd90-4ff5-9d32-aa78b1fa52c8.png)
![image](https://user-images.githubusercontent.com/59545209/178970931-66655156-db03-4bb7-b71a-1599ea15ce26.png)

**Comment by mrgeneralq** [comment]
Added the autocomplete
