### ISSUE TITLE
Night skipped message showing twice

### ISSUE THREAD

**Issue by mrgeneralq** [mrgeneralq/sleep-most#145]
**Describe the bug**
When trying to sleep with the animation enabled, it would start running the animation for every player in addition to the required count. when the night is skipped, the message would show x additional amount of times (the count) the players went to sleep.

**To Reproduce**

1. have night-cylce animation enabled (required count 1)
2. go to sleep with 2 persons
3. note how the chat says [2/1]
4. wait for the night to be skipped and showing the message twice

**Expected behavior**
Show the message once, do not show the message [2/1] but nothing instead

![image](https://user-images.githubusercontent.com/25779174/188004136-c5051c94-556a-41b7-8483-1575a3e91a4c.png)

**Comment by mrgeneralq** [comment]
Test successful. This is now resolved. it will still show 2/1 (to indicate the amount of players in addition sleeping) but it will no longer show the message twice.

**Comment by SergioMadrid135s** [comment]
That is not a bug, I use version 1.18.2 and 1.17.2 and it only shows 1 time
