### ISSUE TITLE
xAntiAFK, afk exempt support

### ISSUE THREAD

**Issue by YungMage** [mrgeneralq/sleep-most#152]
**Is your feature request related to a problem? Please describe.**
There is no possibility to setup AFK exempt while using the plugin xAntiAFK.

**Describe the solution you'd like**
A way to be able to setup AFK exempt for xAntiAFK the same way you would with essentials.

**Describe alternatives you've considered**
Changing back to essentials: I'd run into the problem of having less options for AFK detection and reactions.
Leaving it off: I'd run into the problem that a server with 4 players and 3 AFK, sleep would be impossible.

**Additional context**
https://www.spigotmc.org/resources/xantiafk-detect-all-afk-players-on-your-server-1-8-1-19.63466/
This is the spigot page for the plugin I was talking about: xAntiAFK

**Comment by mrgeneralq** [comment]
Hello @YungMage 

Thank you for your suggestion.
I believe the only thing stopping me from implementing this is having maven support on their end to integrate sleep-most with it.

I will let you know if there is anything changing to that.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
Hello @YungMage 

As for now it seems that the developer of xAntiAFK is not planning on making it avialable on maven. This would mean that it would be impossible for me to integrate with it.

As for now I will have to close this request and mark it incomplete.
In case there are any changes within a short amount of time, I will re-open this ticket and inform you.

Kind regards

Quinten
