### ISSUE TITLE
Each time after the storm is skipped, the title "6:00" appears on the screen

### ISSUE THREAD

**Issue by GodDirtman** [mrgeneralq/sleep-most#153]
**Describe the bug**
Each time after the storm is skipped, the title "6:00" (the same that appears after the night skip) appears on the screen for a short period of time.

**To Reproduce**
1. Set weather to storm
2. Go to bed
3. Skip the storm
4. See the title appearing for a second

**Expected behavior**
No title should appear. 

**Screenshots**
![titlebug](https://user-images.githubusercontent.com/115119810/194177705-b24ae8c7-42ab-48af-9712-e428f876f394.png)

**Comment by GodDirtman** [comment]
> Thank you for your report. Is this also happening when the clock-animation flag is disabled?

Nope, it happens only when it's enabled.

**Comment by mrgeneralq** [comment]
Tested and confirmed the bug. Fix will be implemented

**Comment by mrgeneralq** [comment]
Implemented fix. It will be available as of version 5.2.0
