### ISSUE TITLE
Placeholder not working in boss-bar title

### ISSUE THREAD

**Issue by Solzay** [mrgeneralq/sleep-most#154]
**Describe the bug**
The %required% placeholder does not seem to be parsing when used in the boss-bar title.

**To Reproduce**
1. Edit boss-bar title in messages.yml
2. reload sleep-most or restart server
3. sleep in a bed

**Expected behavior**
%required% should show the number of people that currently need to sleep.

**Screenshots**
![required_bossbar](https://user-images.githubusercontent.com/28128877/194743323-dc5c12ae-777f-47d8-8e86-e3db1a1de6d1.png)

**Comment by mrgeneralq** [comment]
Hello @Solzay , 
thank you for your report. 
I believe there was never an intension to implement this in the first place, but I do see why you expect that placeholder to be there.

I'll be looking into it and let you once there is an update.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
Hello @Solzay 

I have looking into this further, and noticed that we might have changed the placeholder message.
Use **%sleeping-required-count%** instead to get the expected result.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
@Villmarksjenta , could you please check if this is up to date with the docs?
