### ISSUE TITLE
Sleepmost/Bloodmoon Advanced related: /lay and /sm sleep skips the bm night

### ISSUE THREAD

**Issue by Villmarksjenta** [mrgeneralq/sleep-most#155]
During a bloodmoon night you should not be able to sleep (unless enabled in bm config of course). If you have the /sm sleep permission or have gsit integration with /lay, you are able to skip the bloodmoon night by executing either of these commands.

Expected behaviour:
As a player I won't be able to skip the night during a bloodmoon, even by using those commands.

**Comment by Villmarksjenta** [comment]
A related bug: If sleeping in bed right before Bloodmoon starts, you are able to skip the night.

**Comment by mrgeneralq** [comment]
Investigation update: this seems to be something related in bloodmoon and not sleep-most. Most likely the time at bloodmoon being considered night is slightly different. As for now, this issue has to be moved to the bloodmoon rpeo.
