### ISSUE TITLE
Make it so we can edit the time & arrows

### ISSUE THREAD

**Issue by athernalz** [mrgeneralq/sleep-most#157]
![image](https://user-images.githubusercontent.com/97809771/200059246-f2fdf3fa-41eb-47ea-be22-462e15680350.png)

I would love to change the color of the time and arrows and maybe even the bottom text to say something else

**Comment by mrgeneralq** [comment]
Hello @athernalz 

Investigation is pending on whether this can be done.
We keep you posted.

Kind regards

Quinten

**Comment by mrgeneralq** [comment]
Hello @athernalz 

Thank you for your suggestion. This option will be available in the next release (5.2.0).
Placeholder %time% introduced along with 2 messages in the messages.yml

![Time clock can now be changed](https://user-images.githubusercontent.com/25779174/209720265-7dc43d41-8977-4ae8-96b5-8fa3bffd49c2.png)

Kind regards

Quinten
