### ISSUE TITLE
Display the number of ppl sleeping as toast 

### ISSUE THREAD

**Issue by yipjunkai** [mrgeneralq/sleep-most#158]
Rather than spamming the chat with 1/3 players are sleeping, maybe implement the notification as an advancement toasts.

**Comment by mrgeneralq** [comment]
Hello @yipjunkai 

Thank you for your proposal. I've been looking into the toast, but this would require custom advancements which I believe sleeping is not really considered an advancement. In case you don't want the message to be visible you can make the message in the messages.yml an empty text. Like so: ''

You can still use PlaceholderAPI to use sleep-most placeholders and show messages.

More on placeholders here:
https://mrgeneralq.gitbook.io/sleepmost/placeholders/placeholder-api

Kind regards
Quinten
