### ISSUE TITLE
Compatability with Supervanish?

### ISSUE THREAD

**Issue by xSepticSidx** [mrgeneralq/sleep-most#159]
If at nighttime someone selects a bed to sleep and there are i.e. 4 players on the server they see a text in the middle of the screen for a brief moment that says something like "1 of 4 sleeping".

On 1.19.2 when also having Supervanish installed, if an admin goes into vanish so tab shows 3 players the player that sleeps still sees the message telling them there are 4 players - this means they can tell if admin are in vanish.

**Describe the solution you'd like**
Compatability with supervanish and essentialsx vanish so that it does not display vanished players in this player count.
https://www.spigotmc.org/resources/supervanish-be-invisible.1331/

**Describe alternatives you've considered**
cannot think of any.

**Additional context**
I would add a screenshot but its so fast at happening.

**Comment by mrgeneralq** [comment]
Hello @xSepticSidx 

Thank you for your suggestion. I've been looking into the super vanish API, and from there it seems we can integrate it with sleep-most. The next release of sleep-most will contain super-vanish integration.

Kind regards

Quinten
