### ISSUE TITLE
[Feature Request] Exemption and Skipping Vanished Players

### ISSUE THREAD

**Issue by alexis-evelyn** [mrgeneralq/sleep-most#17]
There should be a way to exempt players from the sleep counter. The permission should be sleepmost.exempt and players that are currently vanished (e.g. mods) should also be exempt. I use protocolvanish, but essential's vanish is also a popular type of vanish.

**Comment by mrgeneralq** [comment]
Good morning

Thank you for your report. We will be looking into integrating PlaceHolder API.

Best regards,

Quinten Van den Berghe

**Comment by marvinej** [comment]
I agree that sleepmost.exempt should be a permission node added. I had my developer make this change form me. If you could add it in to the plugin that would be nice. I don't see how vanish is relevant. just give those players the exempt node.

**Comment by mrgeneralq** [comment]
Hello

It has been requested and it will be added.

Kind regards,

Quinten

**Comment by mrgeneralq** [comment]
This issue is resolved as of sleep-most v3.6.1
