### ISSUE TITLE
Add option to disable update checker in config

### ISSUE THREAD

**Issue by TwinkleToes777** [mrgeneralq/sleep-most#178]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when sleep-most does update check and I see it in my firewall and I can't disable it in any normal way. I want my network traffic free of unwanted requests.

**Describe the solution you'd like**
Add update-checker: true/false option to config that does not do any update check requests when set to false.

**Comment by mrgeneralq** [comment]
this option already exists
