### ISSUE TITLE
Lag Issue

### ISSUE THREAD

**Issue by marvinej** [mrgeneralq/sleep-most#19]
Plugin sleep-most is performing a blocking I/O operation (Socket: https://api.spigotmc.org/legacy/update.php?resource=60623) on the main thread. This could affect the server performance, because the thread pauses until it gets the response. Such operations should be performed asynchronous from the main thread. If this happens on server startup, fixing it can drastically reduce startup time. Keep in mind to keep the code thread-safe. Report it to the plugin author

**Comment by samnyan** [comment]
https://github.com/mrgeneralq/sleep-most/commit/4ad62cfc7735159b6197b5f014bf14d9125e0c4e

So I'm running a server with bad connection to spigotmc.org. This causing when a user that has sleepmost.alerts permission to join my server, it will hang at http request and causing watchdog to restart the whole server

**Comment by mrgeneralq** [comment]
This issue is now resolved. The checker has been moved to a different thread. Please let me know if you encounter any more issues.

**Comment by mrgeneralq** [comment]
Re-opened for other thread issue

**Comment by mrgeneralq** [comment]
Issue resolved, fix included as of sleep-most version 3.6.1
