### ISSUE TITLE
Annoying message

### ISSUE THREAD

**Issue by Coding-Kiwi** [mrgeneralq/sleep-most#26]
Hi, awesome and simple plugin!

Is there a way to stop this message from permanently appearing?

![image](https://user-images.githubusercontent.com/5007641/76012419-898f2380-5f16-11ea-9945-06308bf882a2.png)

**Comment by mrgeneralq** [comment]
Hello Coding-Kiwi

Thank you for your feedback. You will get this notifications if you have the permission "sleepmost.notify" . If you got all permissions, but you don't want to see the message, simply negate your permission.

Like so:    -sleepmost.notify     (**note the '-' at the beginning**)

Kind regards,

Quinten

**Comment by mrgeneralq** [comment]
No issue
