### ISSUE TITLE
Plugin sleep-most is performing a blocking I/O operation

### ISSUE THREAD

**Issue by marvinej** [mrgeneralq/sleep-most#28]
This seems to still be an issue.

https://pastebin.com/UR2yn5vY

**Comment by mrgeneralq** [comment]
Hello Marvin

At this point, I'm  running it on a different thread. Could you please let me know if the issue still exists? Thank you for the feedback and have a nice day.

Kind regards,

Quinten

**Comment by mrgeneralq** [comment]
No more response
